[project]
name = "my-hive-engine-tokens-snapshot"
version = "1.5"
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
